services:
  postgres:
    image: postgres:16-alpine
    container_name: rent-cars-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: rentcars
      POSTGRES_USER: rentcars
      POSTGRES_PASSWORD: rentcars
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
